
// Generated by js_of_ocaml 2.7
(function(B){"use strict";var
R="Sys_error",ab=224,aa="Invalid_argument",n=1024,Q=57343,$=512,_="End_of_file",Z="Failure",P="Undefined_recursive_module",Y="Stack_overflow",e=128,d="",x=" : file already exists",M=2048,N=56320,O=240,a=248,X="Not_found",K="Assert_failure",L="/",V="Sys_blocked_io",W="fd ",J="Out_of_memory",U="Match_failure",T="Division_by_zero",S=1e3;function
ag(a){if(a.length<24){for(var
b=0;b<a.length;b++)if(a.charCodeAt(b)>127)return false;return true}else
return!/[^\x00-\x7f]/.test(a)}function
aM(a){for(var
h=d,c=h,b,j,f=0,i=a.length;f<i;f++){b=a.charCodeAt(f);if(b<e){for(var
g=f+1;g<i&&(b=a.charCodeAt(g))<e;g++);if(g-f>$){c.substr(0,1);h+=c;c=d;h+=a.slice(f,g)}else
c+=a.slice(f,g);if(g==i)break;f=g}if(b<M){c+=String.fromCharCode(192|b>>6);c+=String.fromCharCode(e|b&63)}else
if(b<55296||b>=Q)c+=String.fromCharCode(ab|b>>12,e|b>>6&63,e|b&63);else
if(b>=56319||f+1==i||(j=a.charCodeAt(f+1))<N||j>Q)c+="\xef\xbf\xbd";else{f++;b=(b<<10)+j-56613888;c+=String.fromCharCode(O|b>>18,e|b>>12&63,e|b>>6&63,e|b&63)}if(c.length>n){c.substr(0,1);h+=c;c=d}}return h+c}function
aG(a,b){if(b.repeat)return b.repeat(a);var
c=d,e=0;if(a==0)return c;for(;;){if(a&1)c+=b;a>>=1;if(a==0)return c;b+=b;e++;if(e==9)b.slice(0,1)}}function
aP(a,b,c){var
e=new
Array(c);for(var
d=0;d<c;d++)e[d]=a[b+d];return e}function
A(a,b,c){var
e=String.fromCharCode;if(b==0&&c<=4096&&c==a.length)return e.apply(null,a);var
f=d;for(;0<c;b+=n,c-=n)f+=e.apply(null,aP(a,b,Math.min(c,n)));return f}function
ae(a){if(a.t==2)a.c+=aG(a.l-a.c.length,"\0");else
a.c=A(a.c,0,a.c.length);a.t=0}function
aL(a){for(var
l=d,f=d,i,h,j,b,c=0,k=a.length;c<k;c++){h=a.charCodeAt(c);if(h<e){for(var
g=c+1;g<k&&(h=a.charCodeAt(g))<e;g++);if(g-c>$){f.substr(0,1);l+=f;f=d;l+=a.slice(c,g)}else
f+=a.slice(c,g);if(g==k)break;c=g}b=1;if(++c<k&&((j=a.charCodeAt(c))&-64)==e){i=j+(h<<6);if(h<ab){b=i-12416;if(b<e)b=1}else{b=2;if(++c<k&&((j=a.charCodeAt(c))&-64)==e){i=j+(i<<6);if(h<O){b=i-925824;if(b<M||b>=55295&&b<57344)b=2}else{b=3;if(++c<k&&((j=a.charCodeAt(c))&-64)==e&&h<245){b=j-63447168+(i<<6);if(b<65536||b>1114111)b=3}}}}}if(b<4){c-=b;f+="\ufffd"}else
if(b>65535)f+=String.fromCharCode(55232+(b>>10),N+(b&1023));else
f+=String.fromCharCode(b);if(f.length>n){f.substr(0,1);l+=f;f=d}}return l+f}function
aK(a){switch(a.t){case
9:return a.c;default:ae(a);case
0:if(ag(a.c)){a.t=9;return a.c}a.t=8;case
8:return aL(a.c)}}function
h(a,b,c){this.t=a;this.c=b;this.l=c}h.prototype.toString=function(){return aK(this)};function
ah(a){var
b=9;if(!ag(a))b=8,a=aM(a);return new
h(b,a,a.length)}function
aD(a,b){throw[0,a,b]}function
c(a){return new
h(0,a,a.length)}function
ak(a,b){aD(a,c(b))}var
f=[0];function
g(a){ak(f.Sys_error,a)}function
ax(a){if(!a.opened)g("Cannot flush a closed channel");if(a.buffer==d)return 0;if(a.output)switch(a.output.length){case
2:a.output(a,a.buffer);break;default:a.output(a.buffer)}a.buffer=d;return 0}function
af(a){ak(f.Invalid_argument,a)}function
l(a){if(a<0)af("String.create");return new
h(a?2:9,d,a)}var
al=0;function
aQ(){return new
Date().getTime()/S}function
C(){return Math.floor(aQ())}function
i(a){this.data=a;this.inode=al++;var
b=C();this.atime=b;this.mtime=b;this.ctime=b}i.prototype={truncate:function(){this.data=l(0);this.modified()},modified:function(){var
a=C();this.atime=a;this.mtime=a}};function
z(a){return a.l}function
aj(a){a=a
instanceof
h?a.toString():a;g(a+": No such file or directory")}var
av=L;function
q(a){a=a
instanceof
h?a.toString():a;if(a.charCodeAt(0)!=47)a=av+a;var
e=a.split(L),b=[];for(var
c=0;c<e.length;c++)switch(e[c]){case"..":if(b.length>1)b.pop();break;case".":break;case"":if(b.length==0)b.push(d);break;default:b.push(e[c]);break}b.orig=a;return b}function
j(){this.content={};this.inode=al++;var
a=C();this.atime=a;this.mtime=a;this.ctime=a}j.prototype={exists:function(a){return this.content[a]?1:0},mk:function(a,b){this.content[a]=b},get:function(a){return this.content[a]},list:function(){var
a=[];for(var
b
in
this.content)a.push(b);return a},remove:function(a){delete
this.content[a]}};var
s=new
j();s.mk(d,new
j());function
y(a){var
b=s;for(var
c=0;c<a.length;c++){if(!(b.exists&&b.exists(a[c])))aj(a.orig);b=b.get(a[c])}return b}function
aJ(a){var
c=q(a),b=y(c);return b
instanceof
j?1:0}function
aH(a){return new
h(4,a,a.length)}function
ad(a){var
c=new
Array(a.l),e=a.c,d=e.length,b=0;for(;b<d;b++)c[b]=e.charCodeAt(b);for(d=a.l;b<d;b++)c[b]=0;a.c=c;a.t=4;return c}function
aR(a){if(a.t!=4)ad(a);return a.c}function
aw(a,b){var
f=q(a),d=s;for(var
k=0;k<f.length-1;k++){var
e=f[k];if(!d.exists(e))d.mk(e,new
j());d=d.get(e);if(!(d
instanceof
j))g(f.orig+x)}var
e=f[f.length-1];if(d.exists(e))g(f.orig+x);if(b
instanceof
j)d.mk(e,b);else
if(b
instanceof
i)d.mk(e,b);else
if(b
instanceof
h)d.mk(e,new
i(b));else
if(b
instanceof
Array)d.mk(e,new
i(aH(b)));else
if(b.toString)d.mk(e,new
i(c(b.toString())));else
af("caml_fs_register");return 0}function
aI(a){var
b=s,d=q(a),e,f;for(var
c=0;c<d.length;c++){if(b.auto){e=b.auto;f=c}if(!(b.exists&&b.exists(d[c])))return e?e(d,f):0;b=b.get(d[c])}return 1}function
o(a,b,c){if(f.fds===undefined)f.fds=new
Array();c=c?c:{};var
d={};d.file=b;d.offset=c.append?z(b.data):0;d.flags=c;f.fds[a]=d;f.fd_last_idx=a;return a}function
aS(a,b,c){var
d={};while(b){switch(b[1]){case
0:d.rdonly=1;break;case
1:d.wronly=1;break;case
2:d.append=1;break;case
3:d.create=1;break;case
4:d.truncate=1;break;case
5:d.excl=1;break;case
6:d.binary=1;break;case
7:d.text=1;break;case
8:d.nonblock=1;break}b=b[2]}var
h=a.toString(),j=q(a);if(d.rdonly&&d.wronly)g(h+" : flags Open_rdonly and Open_wronly are not compatible");if(d.text&&d.binary)g(h+" : flags Open_text and Open_binary are not compatible");if(aI(a)){if(aJ(a))g(h+" : is a directory");if(d.create&&d.excl)g(h+x);var
i=f.fd_last_idx?f.fd_last_idx:0,e=y(j);if(d.truncate)e.truncate();return o(i+1,e,d)}else
if(d.create){var
i=f.fd_last_idx?f.fd_last_idx:0;aw(a,l(0));var
e=y(j);return o(i+1,e,d)}else
aj(a)}o(0,new
i(l(0)));o(1,new
i(l(0)));o(2,new
i(l(0)));function
ay(a){var
b=f.fds[a];if(b.flags.wronly)g(W+a+" is writeonly");return{file:b.file,offset:b.offset,fd:a,opened:true,refill:null}}function
ac(a,b,c,d,e){if(e==0)return 0;if(d==0&&(e>=c.l||c.t==2&&e>=c.c.length)){c.c=a.t==4?A(a.c,b,e):b==0&&a.c.length==e?a.c:a.c.substr(b,e);c.t=c.c.length==c.l?0:2}else
if(c.t==2&&d==c.c.length){c.c+=a.t==4?A(a.c,b,e):b==0&&a.c.length==e?a.c:a.c.substr(b,e);c.t=c.c.length==c.l?0:2}else{if(c.t!=4)ad(c);var
g=a.c,h=c.c;if(a.t==4)for(var
f=0;f<e;f++)h[d+f]=g[b+f];else{var
i=Math.min(e,g.length-b);for(var
f=0;f<i;f++)h[d+f]=g.charCodeAt(b+f);for(;f<e;f++)h[d+f]=0}}return 0}function
aN(a){if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
b=B.console;b&&b.error&&b.error(a)}function
aO(a){if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
b=B.console;b&&b.log&&b.log(a)}var
r=new
Array();function
aF(a,b){var
h=c(b),d=z(h),g=z(a.file.data),f=a.offset;if(f+d>=g){var
e=l(f+d);ac(a.file.data,0,e,0,g);ac(h,0,e,f,d);a.file.data=e}a.offset+=d;a.file.modified();return 0}function
ai(a){var
b;switch(a){case
1:b=aO;break;case
2:b=aN;break;default:b=aF}var
e=f.fds[a];if(e.flags.rdonly)g(W+a+" is readonly");var
c={file:e.file,offset:e.offset,fd:a,opened:true,buffer:d,output:b};r[c.fd]=c;return c}function
az(){var
a=0;for(var
b
in
r)if(r[b].opened)a=[0,r[b],a];return a}function
aB(a){return a
instanceof
Array?a[0]:a
instanceof
h?252:S}function
b(a,b,c){f[a+1]=b;if(c)f[c]=b}var
aA={};function
au(a){if((a.t&6)!=0)ae(a);return a.c}function
aE(a,b){aA[au(a)]=b;return 0}var
aC=0;function
m(a){a[2]=aC++;return a}b(11,[a,c(P),-12],P);b(10,[a,c(K),-11],K);b(9,[a,c(V),-10],V);b(8,[a,c(Y),-9],Y);b(7,[a,c(U),-8],U);b(6,[a,c(X),-7],X);b(5,[a,c(T),-6],T);b(4,[a,c(_),-5],_);b(3,[a,c(aa),-4],aa);b(2,[a,c(Z),-3],Z);b(1,[a,c(R),-2],R);b(0,[a,c(J),-1],J);m([a,c("Pervasives.Exit"),0]);ay(0);ai(1);ai(2);m([a,c("Array.Bottom"),0]);m([a,c("Sys.Break"),0]);m([a,c("CamlinternalFormat.Type_mismatch"),0]);var
D=[0,0],aq=c("Js.Error"),as=c("h2"),ar=c("p"),at=c("Dom_html.Canvas_not_available");function
E(a){D[1]=[0,a,D[1]];return 0}var
t=B,ap=t.Array,F=m([a,aq,0]),u=[0,F,{}],ao=undefined,an=aB(u)===a?u:u[1];aE(c("jsError"),an);E(function(a){return a[1]===F?[0,ah(a[2].toString())]:0});E(function(a){return a
instanceof
ap?0:[0,ah(a.toString())]});function
v(a,b){a.appendChild(b);return 0}var
k=t.document;function
G(a,b){return a.createElement(b.toString())}function
H(a){return G(a,ar)}m([a,at,0]);t.HTMLElement===ao;var
I=G(k,as),p=H(k),w=H(k);k.title="Hello world";I.textContent="Hello world from ml file";v(k.body,I);p.innerHTML="I'm a paragraph and I'm containing another paragraph";p.id="p_container";w.innerHTML="I'm a paragraph and I'm in a paragraph";w.id="p_in";v(p,w);v(k.body,p);function
am(a){var
b=a;for(;;){if(b){var
c=b[2],d=b[1];try{ax(d)}catch(f){}var
b=c;continue}return 0}}am(az(0));return}(function(){return this}()));
